
custom_css:
  #é¼ æ ‡æ ·å¼
  cursor:
    enable: true
    text: volantis-static/media/cursor/text.png # https://gcore.jsdelivr.net/gh/inkss/common@1/cursor/text.png
    pointer: volantis-static/media/cursor/pointer.png # https://gcore.jsdelivr.net/gh/inkss/common@1/cursor/pointer.png
    default: volantis-static/media/cursor/left_ptr.png # https://gcore.jsdelivr.net/gh/inkss/common@1/cursor/left_ptr.png
    not-allowed: volantis-static/media/cursor/circle.png # https://gcore.jsdelivr.net/gh/inkss/common@1/cursor/circle.png
    zoom-out: volantis-static/media/cursor/zoom-out.png # https://gcore.jsdelivr.net/gh/inkss/common@1/cursor/zoom-out.png
    zoom-in: volantis-static/media/cursor/zoom-in.png # https://gcore.jsdelivr.net/gh/inkss/common@1/cursor/zoom-in.png
    grab: volantis-static/media/cursor/openhand.png # https://gcore.jsdelivr.net/gh/inkss/common@1/cursor/openhand.png

  navbar:
    height: 64px
    width: auto # auto, max
    effect: [ shadow, blur ] # [shadow, floatable, blur]

sidebar:
  # ä¾§è¾¹æ ç»„ä»¶åº“
  widget_library:
    # ---------------------------------------
    # blogger info widget
    blogger:
      avatar: https://s2.loli.net/2023/02/01/QT9rs6EoO7Xq4I5.jpg #volantis-static/media/org.volantis/blog/Logo-NavBar@3x.png # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
      title: æ»•ç¬‘ç„¶
    donate:
      class: qrcode
      display: [desktop, mobile] # [desktop, mobile]
      height: 200px  # Automatic height if not set
      images:
#        - https://gcore.jsdelivr.net/gh/volantis-x/cdn-org/blog/qrcode/github@volantis.png
        - https://s2.loli.net/2023/05/24/T3Fe4XuIrdCRVn5.jpg
    lastupdate:
      class: lastupdate
      display: [ desktop, mobile ]
      header:
        icon: fa-solid fa-clock WISTERIA
        title: æœ€è¿‘æ›´æ–°
navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: https://s2.loli.net/2023/02/01/KqsmDBXC6PYHR3a.png
    icon: https://s2.loli.net/2023/02/01/XnWLTM37mYyF1Q6.png

cover:
  logo: https://s2.loli.net/2023/02/01/3zOucySxfkNnhI5.png #http://rew00265f.hb-bkt.clouddn.com/image/2022/07/12/wu_1g7o7jj1s2kiu6613vvedo1cob6.jpeg
  title: æ»•ç¬‘ç„¶ #onestyle #'ç‘”å¯’ç§‘æŠ€'

### è‡ªå®šä¹‰å³é”® æ–°
rightmenus:
  enable: true
  # å³é”®èœå•é¡¹åŠåŠ è½½é¡ºåº
  # å†…å®¹ç¤ºä¾‹ï¼šplugins.[ç»„å], menus.[ç»„å], hr(åˆ†å‰²çº¿ï¼Œæ¨èå»çº¿ç•™ç™½), music(éŸ³ä¹æ§åˆ¶å™¨)
  order:
    - plugins.navigation
    - hr
    - plugins.inputBox
    - plugins.seletctText
    - plugins.elementCheck
    - plugins.elementImage
    - menus.link
    - hr
    - menus.darkMode
    - plugins.articlePage
    - music
  # åŸºç¡€é¡¹è®¾ç½®
  options:
    # å›¾æ ‡å‰ç¼€ fa-solid, fa-regular, fa-light, fa-thin, fa-duotone, fa-brands
    iconPrefix: fa-solid
    # ä¾‹å¤–ï¼Œåœ¨ articlePage ç»„æ˜¾ç¤ºæ—¶ï¼ˆæ–‡ç« é¡µï¼‰æ—¶ä¾æ—§æ˜¾ç¤ºå« link å±æ€§çš„èœå•é¡¹
    articleShowLink: false
    # å½“è®¾å®šå…¨å±€éŸ³ä¹æ’­æ”¾å™¨æ—¶ï¼Œæ˜¯å¦ä¸€ç›´æ˜¾ç¤ºéŸ³ä¹æ§åˆ¶èœå•ã€‚falseï¼šä»…å½“éŸ³ä¹æ’­æ”¾æ—¶å¯ç”¨
    musicAlwaysShow: false
  # å³é”®å†…ç½®ç»„ï¼Œé¢„ç½®å®ç°
  plugins:
    # å¯¼èˆªç»„ä»¶
    # æ¨ªå‘æ’åˆ—ï¼Œå…±ç”¨ä¸€è¡Œï¼Œä»…æ˜¾ç¤ºå›¾æ ‡ (åŸåˆ™ä¸Šæ”¯æŒçš„æ•°é‡ä¸é™)
    navigation:
      - {id: 'left', name: 'è½¬åˆ°ä¸Šä¸€é¡µ', icon: 'fa-solid fa-arrow-left', event: 'history.back()', group: 'navigation'}
      - {id: 'right', name: 'è½¬åˆ°ä¸‹ä¸€é¡µ', icon: 'fa-solid fa-arrow-right', event: 'history.forward()', group: 'navigation'}
      - {id: 'redo', name: 'åˆ·æ–°å½“å‰é¡µé¢', icon: 'fa-solid fa-redo', event: 'window.location.reload()', group: 'navigation'}
      - {id: 'up', name: 'å›åˆ°é¡¶éƒ¨', icon: 'fa-solid fa-arrow-up', event: 'VolantisApp.scrolltoElement(volantis.dom.bodyAnchor)', group: 'navigation'}
      #- {id: 'home', name: 'å›åˆ°é¦–é¡µ', icon: 'fa-solid fa-home', link: '/', group: 'navigation'}
    # æ–‡æœ¬è¾“å…¥æ¡†ç›¸å…³ç»„ä»¶
    # ç”Ÿæ•ˆäº input/textareaï¼Œç²˜è´´ã€å‰ªåˆ‡ã€å…¨é€‰
    inputBox:
      - {id: 'copyPaste', name: 'ç²˜è´´æ–‡æœ¬', icon: 'fa-solid fa-paste', event: 'copyPaste', group: 'inputBox'}
      - {id: 'copyAll', name: 'å…¨é€‰æ–‡æœ¬', icon: 'fa-solid fa-object-ungroup', event: 'copyAll', group: 'inputBox'}
      - {id: 'copyCut', name: 'å‰ªåˆ‡æ–‡æœ¬', icon: 'fa-solid fa-cut', event: 'copyCut', group: 'inputBox'}
    # æ–‡æœ¬é€‰ä¸­ç±»ç»„ä»¶
    # ç”Ÿæ•ˆäºå³é”®é€‰ä¸­æ–‡æœ¬ï¼Œ__text__ ä¸ºé€‰ä¸­çš„æ–‡æœ¬ã€‚
    seletctText:
      - {id: 'copyText', name: 'å¤åˆ¶æ–‡æœ¬', icon: 'fa-solid fa-copy', event: 'copyText', group: 'seletctText'}
      - {id: 'searchWord', name: 'ç«™å†…æœç´¢', icon: 'fa-solid fa-search', event: 'OpenSearch(__text__)', group: 'seletctText'}
      - {id: 'bingSearch', name: 'å¿…åº”æœç´¢', icon: 'fa-solid fa-search', event: 'window.open(`https://cn.bing.com/search?q=${__text__}`)', group: 'seletctText'}
      - {id: 'googleSearch', name: 'è°·æ­Œæœç´¢', icon: 'fa-solid fa-search', event: 'window.open(`https://www.google.com/search?q=${__text__}`)', group: 'seletctText'}
    # é“¾æ¥åˆ¤æ–­ç»„ä»¶
    # ç”Ÿæ•ˆäºé“¾æ¥å¤„çš„å³é”®è¡Œä¸ºï¼Œ__link__ ä¸ºé“¾æ¥åœ°å€
    elementCheck:
      - {id: 'openTab', name: 'æ–°æ ‡ç­¾é¡µæ‰“å¼€', icon: 'fa-solid fa-external-link-square-alt', event: 'window.open(__link__)', group: 'elementCheck'}
      - {id: 'copyLink', name: 'å¤åˆ¶é“¾æ¥åœ°å€', icon: 'fa-solid fa-link', event: 'copyLink', group: 'elementCheck'}
    # å›¾ç‰‡åˆ¤æ–­ç±»ç»„ä»¶
    # ç”Ÿæ•ˆäºå›¾ç‰‡ç±»çš„å³é”®è¡Œä¸ºï¼Œ__link__ ä¸ºé“¾æ¥åœ°å€
    elementImage:
      - {id: 'copyImg', name: 'å¤åˆ¶å›¾ç‰‡', icon: 'fa-solid fa-image', event: 'copyImg', group: 'elementImage'}
      - {id: 'googleImg', name: 'è°·æ­Œè¯†å›¾', icon: 'fa-solid fa-images', event: 'window.open(`https://www.google.com.hk/searchbyimage?image_url=${__link__}`)', group: 'elementImage'}
    # æ–‡ç« é¡µé¢ç»„ä»¶
    # ç”Ÿæ•ˆäº post.article é¡µé¢
    articlePage:
      - {id: 'printMode', name: 'æ‰“å°é¡µé¢', icon: 'fa-solid fa-print', event: 'printMode', group: 'articlePage'}
      - {id: 'readMode', name: 'é˜…è¯»æ¨¡å¼', icon: 'fa-solid fa-book-open', event: 'readMode', group: 'articlePage'}
  # å³é”®è‡ªå®šä¹‰èœå•åŒºåŸŸ
  menus:
    link:
      - {id: 'help', name: 'å¸¸è§é—®é¢˜', icon: 'fa-solid fa-question', link: 'https://volantis.js.org/faqs/', group: 'link'}
      - {id: 'examples', name: 'ä¸å¤Ÿè¯¦ç»†ï¼Ÿçœ‹çœ‹ç¬”è®°', icon: 'fa-solid fa-rss', link: 'https://logseq.onestyle.top/', group: 'link'}
      - {id: 'contributors', name: 'è®¿é—®navå¯¼èˆª', icon: 'fa-solid fa-fan', link: 'http://nav.onestyle.top/', group: 'link'}
      - hr
      - {id: 'source_docs', name: 'æœ¬ç«™æºç ', icon: 'fa-solid fa-code-branch', link: 'https://github.com/snake34475/snake34475.github.io', group: 'link'}
      - {id: 'source_theme', name: 'ä¸»é¢˜æºç ', icon: 'fa-solid fa-code-branch', link: 'https://github.com/volantis-x/hexo-theme-volantis/', group: 'link'}
    darkMode:
      - {id: 'darkMode', name: 'æš—é»‘æ¨¡å¼', icon: 'fa-solid fa-moon', event: 'volantis.dark.toggle()', group: 'darkMode'}

#è¯„è®ºç³»ç»Ÿ
#comments:
#  service: beaudar
#  # beaudar
##   https://beaudar.lipk.org/
#  beaudar:
#    repo: snake34475/snake34475.github.io
#    issue-term: pathname
#    issue-number:
#    branch: main
#    position: top
#    order: desc
#    theme:
#      light: github-light
#      dark: github-dark
#    label: âœ¨ğŸ’¬âœ¨


comments:
  service: giscus
  # giscus
  # https://giscus.app
  # https://github.com/laymonage/giscus
  giscus:
    # ä»¥ä¸‹é…ç½®æŒ‰ç…§ yml æ ¼å¼å¢åˆ å¡«å†™å³å¯
     repo: snake34475/snake34475.github.io
     repo-id: R_kgDOHo7Tiw
     category: General
     category-id: DIC_kwDOHo7Ti84CWtGh
     mapping: "pathname"
     reactions-enabled: "1"
     emit-metadata: "0"
     lang: "zh-CN"
     loading: 'lazy'
    # ä»¥ä¸Šé…ç½®æŒ‰ç…§ yml æ ¼å¼å¢åˆ å¡«å†™å³å¯
     theme:
        light: "light" # https://gcore.jsdelivr.net/gh/volantis-x/cdn-volantis@master/css/giscus/light.css
        dark: "dark" # https://gcore.jsdelivr.net/gh/volantis-x/cdn-volantis@master/css/giscus/dark.css


site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [aplayer, social, license, analytics, info, copyright]
  social:
    - icon: #fa-solid fa-rss
      url:
    # or
    - img:
      url:
    # or
    - avatar:
      url:
  # site source
  source: https://github.com/volantis-x/volantis-docs/
  # site copyright
  copyright: 'è±«ICPå¤‡2022018466å·-1'
